# Spark solo reporta errores para que no ensucie las salidas de los cuadernos
rootLogger.level = error
rootLogger.appenderRef.stdout.ref = consola
logger.repl.name = org.apache.spark.repl.Main
logger.repl.level = error

appender.console.type = Console
appender.console.name = consola
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n
